POST http://localhost:5000/app/??
Content-Type: /application/json
{
    "owner": "0x56894y5trg849yu3y695j5gj9",
    askingprice: 1000000,
    street: "1 Dover Road",
    city: "Singapore",
    state: "Singapore",
    country: "Singapore",
    zipcode: "123456",
    description: "sent from test.http",
    propertytype: "Townhouse",
    builtsize: 20000,
    landsize: 5000,
    yearbuilt: 1997,
    occupancy: 90.5,
    annualgrossrent: 300000,
    annualexpenses: 200000,
    noi: 100000,
    expectedyield: 11.8
}